### PR TITLE
GH Actions to build firmware

### PR DESCRIPTION
**Pull request by Jason2866**
upload the builded firmware in section release when drafting a release tagging like `v*.*.*`

### CODE REVIEW

**Comment by mightymos** [comment]
Thanks for the PR. Sorry, I am on Windows with msys2 which supports bash and pacman package manager. Is it possible or desired to accommodate Windows?

**Comment by Jason2866** [comment]
Why is the platform relevant where the Firmware is built?
Or is related to maintaining?
If maintaining is the reason, i do understand. Setting up an GH Windows env to build is not so easy. Imho a bit strange since in the end an Linux system is used.
Stopped using Windows in 2021. Happy with a Macbook Air M1. Awesome performance.
Tbh. Dont know how to install the needed stuff in GH Windows env for this.

**Comment by mightymos** [comment]
I did not understand where a GH Action runs at first. Merging.

**Comment by Jason2866** [comment]
@mightymos Forgot, the GH actions needs write permissions to publish the release.
You find that in GH settings -> Actions -> General
577F8F0E-20C7-4F6D-9AD7-3462628B0B3A

**Comment by mightymos** [comment]
I show identical settings to your screenshot by default.
Am I missing something else?

**Comment by Jason2866** [comment]
Probably not. To start the action you have to draft a release
637CF0AA-4E73-4BA0-B856-B358FE69E0CE
Push the menu button "Drafta new release" and choose a version number you want in format `v*.*.*`
and than push publish menu button

**Comment by Jason2866** [comment]
If you do some GH Actions, you get addicted to ;-)

**Comment by mightymos** [comment]
Got it, thanks. There are actually two different parts in these door sensors so far...that run at different system clocks. The makefile and generated hex file would probably need to take this into account in the future.

**Comment by Jason2866** [comment]
Maybe you can do a Makefile which is building all different variants?
Small change for releasing all builded variants.

**Comment by mightymos** [comment]
Yes, will be needed eventually. I will have to learn more about makefiles.

**Pull request merged**
